### ISSUE TITLE
ObjectiveSense belongs to solverinstance or to the objective function?

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#110]
`ObjectiveSense` is an attribute but it is also set in `setobjective!`.
It looks like `ObjectiveSense` belongs to the objective and thus could be modified by `modifyobjective!` instead of `setattribute`.

Where it belongs? Both places?

**Comment by mlubin** [comment]
What about removing `setobjective!` and using the `ObjectiveFunction` and `ObjectiveSense` attributes instead? `modifyobjective!` would stay though, because that functionality isn't available through setting attributes.

**Comment by blegat** [comment]
It would be consistent to keep the parallel between constraint and objective where the objective sense plays the role of the constraint set. In that case, we just need to allow `modifyobjective!(m, ::OptimizationSense)` the same way we allow `modifyconstraint!(m, ref, set)`

**Comment by mlubin** [comment]
`setobjective!` and `addconstraint!` are not actually parallel in my mind. `setobjective!` is just a shorthand for setting `ObjectiveFunction` and `ObjectiveSense`. On the other hand, `addconstraint!` is needed because we don't have a way to express "adding to a set" with the current way that we deal with attributes. The real parallel would be between `addconstraint!` and a hypothetical `addobjective!`, but given that we decided against `addobjective!` for now, why not just get rid of `setobjective!`?

**Comment by blegat** [comment]
It is probably a good idea to get rid of `setobjective!` indeed, it would be less work for the solver wrappers.

**Comment by joaquimg** [comment]
I agree with removing `setobjective!` and keeping `modifyobjective!` just for the function part and not for sets, which can be set with `setattribute`.

**Comment by mlubin** [comment]
I'll plan on going ahead with this change unless there's a new objection.
