### ISSUE TITLE
Reference ownership

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#163]
Now that we have `MOI.copy!` (https://github.com/JuliaOpt/MathOptInterface.jl/pull/160), we need to settle a convention for ownership of references:

```julia
src = SolverInstance(solver)
x = addvariable!(src)

dest = SolverInstance(anothersolver)
copy!(dest, src)

# what is the result of
isvalid(dest, x)
```

**Comment by joaquimg** [comment]
I think it should be `true` and that would be very useful. Do you see any drawbacks?

**Comment by mlubin** [comment]
Yes, the numbering of references is implementation defined. We can't force this to work. I would use names to match up variables across two instances. It would be nice to use the type system somehow to make it a compile-time error to use the reference in the wrong instance.

**Comment by joaquimg** [comment]
Oh, now I see. W are allowing to copy between solvers. I was thinking about the same solver, in this second case we can make it happen right?
Given what @mlubin said it should not be guaranteed to return true. However I think we can make it return true for the "same solver" case.

**Comment by joaquimg** [comment]
@odow wrote `solver` on both, did yyou have in mind the "same solver" case?

**Comment by mlubin** [comment]
To respond to the original question: I view a reference as an index into an array that a particular instance owns.

**Comment by odow** [comment]
Edited to reflect that wasn't what I intended.

It's also a problem when adding and deleting variables since the ordering can become jumbled. And depending on how you iterate through constraints, the ordering might change. For example it's natural to go:
```julia
for (F,S) in MOI.get(src, MOI.ListOfConstraints())
    if !MOI.canaddconstraint(dest, func, set)
        error("Unable to add the constraint of type ($(F), $(S))")
    end
    for csrc in MOI.get(src, MOI.ListOfConstraintReferences{F,S}())
        MOI.addconstraint!(dest, ... )
    end
end
```
But that might not be the same order as originally inputted.

> I would use names to match up variables across two instances.
Does this mean that we enfore every variable and constraint to have a unique name?

**Comment by mlubin** [comment]
> Does this mean that we enfore every variable and constraint to have a unique name?

Yes, either unique names or `""`.

**Comment by odow** [comment]
How do we match up variables named `""` though?

**Comment by mlubin** [comment]
You don't.

**Comment by mlubin** [comment]
If we want to be thorough about this, we can make an `InstanceCopier` object that you use to copy one instance into another. It persists after copying and has methods to translate references from one instance to the other.

**Comment by mlubin** [comment]
Maybe we can have a `MOIU.fillnames!` helper method that fills all `""` names with unique names, for the case where you need to reference arbitrary variables or constraints across models. We'll need something like this when dealing with most file formats anyway.

**Comment by mlubin** [comment]
I'll withdraw my objection. Maybe we should require that references remain valid from an old instance to a new instance after `copy!`. See https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/34#issuecomment-348066520.

**Comment by mlubin** [comment]
I think it's a good idea to have this `modelid` field (`instanceid`?), will help catch errors for mismatching references.

So maybe references from a copied instance can be recognized this way? Seems a bit complex for an instance to have to remember the `modelid` of where it was copied from, however.

**Comment by mlubin** [comment]
> `get(dest, ModelID()) == get(src, ModelID()) # true`

How does this work? What happens when you modify `src` after copying from it?

**Comment by odow** [comment]
Having thought about it a bit more, I retract that part of the proposal. All the extra ID is doing is taking the range of uniuqe references from `UInt64` to `UInt64 x UInt64`.

Another option is to advise solvers to use random `UInt64` for their references so that it is highly unlikely that to variables get the same value.

**Comment by mlubin** [comment]
Randomizing `value` is a good idea.

What about this:
```julia

src  = StandaloneInstance()
dest = SolverInstance()

y = addvariable!(src)
isvalid(dest, y) # false
isvalid(src, y)  # true

get(dest, ModelID()) == get(src, ModelID()) # false

referencemap = copy!(dest, src)

isvalid(dest, y) # false
isvalid(dest, referencemap[y]) # true

get(dest, ModelID()) == get(src, ModelID()) # false
```

**Comment by IssamT** [comment]
The value randomization sounds like a dangerous solution. I like more the idea of instanceid but without using them to decide if instances are identical since we can not even ensure, **before copying**:

````julia
get(dest, ModelID()) == get(src, ModelID()) # false
````

The variable references are different (within an instance) because there is a unique entity responsible of that, namely the instance. As long as we had only one instance in a single run this was enough. but if we want to have many instances sharing the variables within a run, we will need another entity to manage the instances. That same entity would be responsible of assigning or at least validating instance ids. 

I also think that all alive instances need to have a unique id (even for copies). However it is still possible for our entity to store mappings of indentical instances (There is a need to track when an instance is modified).

This entity is probably the InstanceManager we have been discussing, and it defines also these functions:

````julia
isidentical(instmanager, src, dest)
copy!(instmanager, dest, src)
````

We can have each instance store its unique manager and define shortcuts like

````julia
function isidentical(src, dest)
    if src.instmanager != dest.instmanager
        #throw error
    else
        return isidentical(src.instmanager, src, dest)
    end
end
````

**Comment by blegat** [comment]
I like the idea of `copy!` returning a dictionary. It makes it clear to the user of `copy!` that the references are different and it needs a mapping. Shouldn't we return both a variable reference and a constraint reference map though ? I don't know that is better (tradeoff of cleaner and faster) between `Dict{MOI.VariableReference}`/`Dict{MOI.ConstraintReference}` and a `Dict{MOI.AnyReference}`.

About the model id, why not do
```julia
struct VariableReference{InstanceType <: AbstractInstance}
    owner::InstanceType
    variable::UInt64
end
```

**Comment by mlubin** [comment]
@IssamT instances can be created on their own. Requiring a "global" instance factory just to manage unique IDs is very complicated, we might as well go with @blegat's suggestion if we do that.

> Shouldn't we return both a variable reference and a constraint reference map though?

The return type doesn't need to be a `Dict`. It can be a dict-like object that supports variable and constraint references efficiently. I don't see the need to return two different objects.

> About the model id, why not do ...

This reasonable but it means that the instance manager (and therefore the JuMP model) need to have a type parameter in order to handle the references efficiently. That's why we decided against it earlier. I might be convinced that this is a good idea, but needs more thought.

**Comment by blegat** [comment]
> The return type doesn't need to be a Dict. It can be a dict-like object that supports variable and constraint references efficiently. I don't see the need to return two different objects.

That's a good idea.

> This reasonable but it means that the instance manager (and therefore the JuMP model) need to have a type parameter in order to handle the references efficiently.

Yes this will complicate things a lot for not much benefit. By the way, as mentionned in #178 ,
I wonder if it is really worth it to double the size of a variable reference just for error handling ? It is a low level interface, we should emphasize lightness more than user friendliness.

**Comment by mlubin** [comment]
https://github.com/JuliaOpt/MathOptInterface.jl/pull/178#issuecomment-348454544

> I wonder if it is really worth it to double the size of a variable reference just for error handling ? It is a low level interface, we should emphasize lightness more than user friendliness.

MOI is emphasizing developer friendliness, and having an API that reports errors instead of having "undefined behavior" is one aspect of that. But @odow's randomization proposal is one way to get around the size increase (and avoiding the need to add a type parameter).

> The value randomization sounds like a dangerous solution.

@IssamT, what's dangerous about it? The `value` field can be thought of as a pointer. Having random pointer addresses doesn't bother anyone. Instances could also "XOR" the values with their `object_id`, and avoid having to use maps.

**Comment by blegat** [comment]
Oh I though randomization of the instance idea. Yes randomization of the constraint and reference ids seems nice. We can rely on the fact that having same random values is unlikely for the error reporting but we shouldn't rely on that for having different references inside the same instance. We should for example have a `Set` with ids already taken by the instance then and do
```julia
id = rand(UInt64)
while id in instance.taken_ids
    id += 1
end
push!(instance.taken_ids, id)
```
or
```julia
id = rand(UInt64)
while id in instance.taken_ids
    id = rand(UInt64)
end
push!(instance.taken_ids, id)
```
It looks scary to have to use a while loop (the second one is even more scary since it relies on good behaviour of rand to not be in an infinite loop) but it should work ok.

**Comment by mlubin** [comment]
@blegat, no need for that. Instances can choose an arbitrary number like `object_id()` or `rand(UInt64)` and just XOR it with the linear values currently being used. XOR is an invertible operation.

**Comment by blegat** [comment]
Oh nice, I didn't think about the XOR trick :-P

**Comment by IssamT** [comment]
> @IssamT, what's dangerous about it?

It is a misleading behavior. And instead of getting rid of it, the value randomization makes it happen rarely. it's the "rarely" that scares me.

**Comment by blegat** [comment]
The user will not rely on this behavior for his code to work. This behavior is there to make a bad code (using reference from the wrong instance) fail more systematically. So it should not scare you.

**Comment by mlubin** [comment]
PR at https://github.com/JuliaOpt/MathOptInterface.jl/pull/179
