### ISSUE TITLE
A "solver" for standalone instances

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#164]
As raised [here](https://github.com/odow/MathOptFormat.jl/pull/14#issuecomment-342039829), what is the parallel of a solver for a standalone instance?

Maybe `solver` is a misnomer and they should be called
 - InstanceCreator
 - Instantiator
 - InstanceGenerator
 - InstanceController

```julia
"""
    AbtractInstantiator

Abstract supertype for "solver" objects.
An instantiator is a lightweight object used for selecting solvers and parameters.
It does not store any solver instance data.
"""
abstract type AbtractInstantiator end

"""
    StandaloneInstance(creator::AbtractInstantiator)::AbstractStandaloneInstance

Create a standalone instance from the given instantiator.
"""
function StandaloneInstance end

"""
    SolverInstance(creator::AbtractInstantiator)::AbstractSolverInstance 

Create a solver instance from the given instantiator.
"""
function SolverInstance end
```

Then you could have something like
```julia
using Gurobi, MathOptInterface, LPFiles

grb = MOI.SolverInstance(GurobiSolver())
MOI.StandaloneInstance(GurobiSolver()) # errors

MOI.SolverInstance(LPFile()) # errors
lp = MOI.StandaloneInstance(LPFile())
```

**Comment by mlubin** [comment]
It's good to discuss this, since the solver concept is something we imported from MPB without much thought. The point of the solver is to hold the arguments for the constructor of an instance in a generic way. Maybe we don't need this anymore?

Here's what it could look like without solver objects:
```julia
m = Model()
.....
JuMP.solve(m) # error: no solver instance attached
JuMP.attach(m, GurobiInstance(TimeLimit=..., env=...))
JuMP.solve(m)
```
This clarifies what JuMP will do internally anyway, so I'm in favor.

**Comment by odow** [comment]
Maybe `SolverInstance` should be called a `WrapperInstance` as it wraps an underlying model without storing the model.

```julia
m = Model() # creates a standalone instance
@variable(m, x >= 0)
@objective(m, Min, x)
c = @constraint(m, 2x >= 2)
JuMP.attach(m, CbcModel())
JuMP.solve(m)
# x = 1
JuMP.setcoefficient!(m, c, x, 4.0) # error: solver is currently attached.
JuMP.detach(m)
JuMP.setcoefficient!(m, c, x, 4.0) # modifies coefficent in standalone instance
JuMP.attach(m, CbcModel())
JuMP.solve(m)
# x = 0.5
```
```julia
# creates a solver (wrapper) instance with no JuMP model stored 
# and all modifications pushed through to the Gurobi model
m = Model(GurobiModel()) 
@variable(m, x >= 0)
@objective(m, Min, x)
c = @constraint(m, 2x >= 2)
JuMP.solve(m)
# x = 1
JuMP.setcoefficient!(m, c, x, 4.0)
JuMP.solve(m)
# x = 0.5
JuMP.detach(m) # error: not a standalone instance
```

**Comment by mlubin** [comment]
What do you mean without storing the model? The model is still stored, it just is owned by the low-level solver.

Yes, there are a few possibilities for how a JuMP model could be attached to a solver instance and/or standalone instance, but first question is deciding if there's any reason to keep the current concept of a solver.

**Comment by mlubin** [comment]
"Wrapper" is also a bit disrespectful to pure-Julia MOI-native solvers :)

**Comment by odow** [comment]
Oh, I didn't realize you meant a total axing of solver objects. 100% for this.
```julia
instance = GurobiInstance(options...)
# is much nicer than
instance = MOI.SolverInstance(GurobiSolver(options...))
```

**Comment by mlubin** [comment]
Yes, complete axing of solver objects.

**Comment by blegat** [comment]
What is the gain of getting rid of `Solver` object ? It is something well-defined and useful. It serves as a factory creating instances. If you want to solve several problems, you need a factory to create an instance for each problem. If you have an empty instance you could copy it but it seems less natural.

Also, the name `SolverInstance` kind of suggest that there is also a `Solver`. For the standalone solver, I like @odow 's suggestions (we could also consider the name `InstanceFactory`).

**Comment by mlubin** [comment]
@blegat, having factory objects is an extra level of complexity that should be justified relative to the cost. Solvers objects are useful for obscuring the points at which instances are created, which seems to go against the MOI philosophy of maximum transparency and no magic. I don't think JuMP itself will need to make copies of instances, and usually one would try to reuse instances instead of creating new ones.

You can always ask the user to give you a function that returns a new instance, i.e., `() -> GurobiInstance()`; this is again much more clear than dealing with solver objects that few people immediately understand. Could you give an example of where going this route would be a big loss in usability?

**Comment by joaquimg** [comment]
About this example:
> ```julia
> m = Model()
> .....
> JuMP.solve(m) # error: no solver instance attached
> JuMP.attach(m, GurobiInstance(TimeLimit=..., env=...))
> JuMP.solve(m)
> ```
I prefer:
```julia
m = Model()
.....
JuMP.solve(m) # error: no solver set
JuMP.setsolver(m, GurobiSolver(TimeLimit=..., env=...))
JuMP.solve(m)
```
I know it was just a first taught, but i think attach might mean that you are attaching multiple solvers.

I don´t see a usability problem, I am totally ok with getting rid os the solver lightweight objects.

However I prefer the second because I think a common user does not care if there is a GurobiInstance inside the jump model, but it wants to solve the model with a Gurobi solver. All in all, I just prefer the name for clarity.

I liked @odow ´s 
> creates a solver (wrapper) instance with no JuMP model stored 
> and all modifications pushed through to the Gurobi model

But I think this is not the core of this thread.

**Comment by mlubin** [comment]
MOI prioritizes developer friendliness and clarity over appearing magical to the common user. Solver objects don't really make sense in that light.

A user-friendly interface could also provide what users *really* expect which is `solver="Gurobi"`, `solver="Cbc"`, etc.

**Comment by mlubin** [comment]
Also +1 for @odow's
> creates a solver (wrapper) instance with no JuMP model stored
and all modifications pushed through to the Gurobi model

**Comment by blegat** [comment]
What if JuMP realize that the solver does not support the modification that the user requires ? It needs to ditch the current instance and create a new one. How do you do that without a factory ?

**Comment by mlubin** [comment]
Julia provides a number of ways to deal with this situation that don't require all MOI wrappers to define solver objects.
For example, after Gurobi defines `GurobiInstance()`, anyone can go ahead and define
```
GurobiSolver(;kwargs..) = () -> GurobiInstance(;kwargs...)
```
So I'd restrict my claims to say that there's no need for solver objects within MOI because they unnecessarily complicate the wrappers and the API, and that whoever needs factories can easily define them later.

**Comment by blegat** [comment]
I agree with that, we could also have something like
```julia
@solver Name{AbstractFloat} verbose=false
```
which would be parsed into
```julia
NameIntance{AbstractFloat}(verbose=false)
```
This kind of construction could live outside of MOI.

However, it seems to me that it is a very common construction (e.g. in SDDP you create hundreds of solver instance of the same solver) and giving it a name and a type (instead of just `Function`) would provide more clarity that confusion.
Without any convention, the API will differ between the applications and it might end up creating confusion to the user.
The `@solver` may solve that and its definition could be outside MOI, maybe in JuMP ?

(I am leaning toward agreeing with you but I am not 100% convinced yet :-P)

**Comment by odow** [comment]
To throw a spanner in the works. What about Gurobi `Env`'s?

```julia
solver = GurobiSolver()

m1 = Model(solver=solver)
m2 = Model(solver=solver)
```
both models utilise the same env. ref https://github.com/JuliaOpt/Gurobi.jl/pull/57

Having users go
```julia
env = Gurobi.Env()
m1 = Model()
JuMP.attach(m1, GurobiInstance(env))
m2 = Model()
JuMP.attach(m2, GurobiInstance(env))
```
isn't any better. Neither is
```julia
grb = GurobiInstance()
m1 = Model()
JuMP.attach(m1, grb)
m2 = Model()
JuMP.attach(m2, grb) # might complain that grb isn't empty
```

**Comment by mlubin** [comment]
There will always be a collection of parameters to pass, `env` isn't particularly special.

If we agree that solvers can be removed from MOI, then we can discuss how to deal with this issue at a higher level. I'd rather this be a code organization question than an MOI API question.

**Comment by mlubin** [comment]
One remaining barrier I see is the `AbstractSolverAttribute`s and `supportsproblem`. We allow `supportsproblem` to depend on the parameters in the solver, but maybe these should just become instance properties.

**Comment by joaquimg** [comment]
I like `supportsproblem` to depend on the current state of the instance. Could it be a `canadd` or something like that? Meaning can I add "this thing" to this instance, and "this thing" could be a set of (constraints/variables/objectives).

**Comment by joaquimg** [comment]
`AbstractSolverAttribute`s are basically `SupportsSomething` would it be that bad to check those on a instance? Instances that were just initialized are not that heavy.
We could recommend:
```julia
instance = GurobiInstance()
get(instance, SupportsThing1)
get(instance, SupportsThing2)
...
get(instance, SupportsThingN)
```
Instead of creating instances for every test.

Actually I am not a big fan of using `get` for those, maybe `isvalid` or I don´t know...

**Comment by mlubin** [comment]
The `SupportsXXX` attributes for solvers don't feel 100% solid for me. Their purpose is not really clear, and they're not always well defined. For example,

- Is the implementation of an algorithm supposed to change based on what a given solver supports? We do this in Pajarito for NLP vs conic solvers, but it's a bit sketchy (@chriscoey). 
- Is `SupportsAddVariableAfterSolve` true or false if you can add a variable and add it to some but not all kinds of constraints?

It may be more important to address how to report invalid requests (https://github.com/JuliaOpt/MathOptInterface.jl/issues/16). My point here is that I don't think losing `AbstractSolverAttribute`s is a big issue, and we can cover same points by querying instances, so I'm out of reasons to keep solver objects around.

**Comment by joaquimg** [comment]
I agree that these attributes are not a problem. The only thing I currently like about the solver is that serting a solver to a jump model makes more sense to me that attaching an instance. But we can do that in some other way.
