### ISSUE TITLE
nonneg polynomial and sum of squares cones (and their duals)?

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#183]
Why not support these directly (rather than just PSD cones)? There are methods like https://arxiv.org/abs/1712.01792 for solving sum of squares problems without SDP. You can see the benefit of their approach in their computational results - starting with a massive reduction in the number of variables. (edit: Joey and) I may be interested in working on an algorithm based on cutting planes.

May be relevant to bridges and the (future?) design of https://github.com/JuliaOpt/SumOfSquares.jl

@blegat @mlubin @joehuchette

**Comment by blegat** [comment]
I like the idea. The definition could be
```julia
struct SumOfSquaresCone{MT} <: AbstractVectorSet
    monomials::Vector{MT}
end
```
where `MT` stands for `MonomialType`. The issue is that the solver would not know how to deal with `monomials` since it does not know which API to use. We could say that it needs to assume that the monomials satisfy the [MultivariatePolynomials API](https://github.com/JuliaAlgebra/MultivariatePolynomials.jl) but then we should have `MT <: AbstractMonomial` which would require MOI to depend on MultivariatePolynomials which is not desirable. One solution could be to just leave `MT` without `MT <: AbstractMonomial` even if it's not very clean, one other solution would be to define this cone in SumOfSquares.jl.
For the dual, the name could be `DualSumOfSquaresCone`, `MomentsCone`, `RelaxedMomentsCone`, `PseudoExpectationCone`, `PseudoMeasureCone`, `PseudoMomentsCone`, ... any other idea :-P ?

SumOfSquares.jl could indeedndefine the SDP reformulation bridge and give it to JuMP or the InstanceManager saying "here is a bridge : if a solver does not support SOS cone just apply the bridge on top of it". That would be a nice design.

While we are at it we could also add the DSOS/SDSOS cones : DiagonallyDominantSymmetricMatrixTriangle, ScaledDiagonallyDominantSymmetricMatrixTriangle, DiagonallyDominantSumOfSquaresCone, ScaledDiagonallyDominantSumOfSquaresCone, DiagonallyDominantPseudoMomentsCone, ScaledDiagonallyDominantPseudoMomentsCone.
If we decide to put SOS cones in SumOfSquares.jl the last 4 would be there too. However the first two could be in MOI (and have their `*Square` counterpart).

**Comment by chriscoey** [comment]
I'm less sure of this now, having done a bit more work with polynomial nonnegativity constraints and their complexities (basis and domain set). It isn't clear yet what sorts of representations we want, but it will become clearer after we resolve https://github.com/JuliaOpt/PolyJuMP.jl/issues/17 and the various implications of having a different polymodule that doesn't use SumOfSquares approximations. So I'm going to table this for now. Until there are solvers that handle these problems without SDP, it seems unnecessary to try to put nonnegative polynomial constraints into MOI.
