### ISSUE TITLE
Use `Pair{VariableIndex, T}` instead of separate variable and coefficient lists

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#211]
Proposed by @tkoolen: In ScalarAffineFunction, why not use a Vector{Pair{VariableIndex, T}}, so as to ensure that you don’t have more coeffs than vars? Same thing for some of the other functions.

Ref #209

**Comment by joaquimg** [comment]
I don’t like Pair. I think it might be interesting having those separate vectors for inplace modifications easily. We can enforce size check on the constructor if thats a big thing

**Comment by tkoolen** [comment]
But then other methods can still push different numbers of things to each of the vectors.

**Comment by mlubin** [comment]
I agree that this is a good idea from the software engineering perspective. I would use a struct instead of a Pair (Pair doesn't generalize well to the quadratic case.)

One concern is that MOI functions usually go through [`mapvariables`](https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/1ea446c08f5d2f32d52b10974992beeb2670b12e/src/functions.jl#L5) at some point in their life. This change would force us to 1) make a more expensive copy that includes the coefficients, or 2) modify the functions in place instead.

**Comment by joaquimg** [comment]
The current design is very easy to modify variable indices or the coefficients. There are cases like cut generation routines that always use the same variable indices and just changes the coefficients. Pair would make this a pain. I don´t see a big gain with that, this error is really easy to catch and solve.

**Comment by tkoolen** [comment]
I agree that a `struct` other than `Pair` would be better.

> There are cases like cut generation routines that always use the same variable indices and just changes the coefficients. Pair would make this a pain.

Is that something a couple of utility functions could fix? Something like
```julia
struct LinearTerm{T}
    variable::VariableIndex
    coefficient::T
end

setvariable(term::LinearTerm, var::VariableIndex) = LinearTerm(variable, term.coefficient)
setcoefficient(term::LinearTerm, coefficient) = LinearTerm(term.variable, coefficient)
```
> this error is really easy to catch and solve.

I disagree. It's really tempting to write code like

```julia
fun = ScalarAffineFunction([VariableIndex(1), VariableIndex(2)], [5.0, -2.3, 3.0], 1.0) # oops

for i in eachindex(fun.variables)
    fun.variables[i] = VariableIndex(3 * i)
    fun.coefficients[i] += 1
end # last coefficient wasn't updated

# and then in some completely different solver package:
for coeff in fun.coefficients
    pushontosomesolverdatastructure!(mysolver, coeff)
end
```
This will silently do the wrong thing due to a bug that occurred in non-local code. The only way to be sure this kind of thing doesn't happen is to tediously check that the `ScalarAffineFunction` is in a valid state everywhere. And then there are even more subtle cases, like erroneously removing a variable from the front of `variables` but removing a coefficient from the back of `coefficients`; now their lengths match, but they're out of sync.

> One concern is that MOI functions usually go through mapvariables at some point in their life

Good point, but if speed is really a concern (which is probably the case), in my opinion `mapvariables` should be in-place whether or not this proposal makes it. I would expect the difference in performance between allocating a `Vector{VariableIndex}` and `Vector{LinearTerm{T}}` to be much smaller than the difference between allocating  a `Vector{VariableIndex}` and not allocating at all.

**Comment by mlubin** [comment]
@blegat, what do you think about making `map_variables` work in place?

**Comment by tkoolen** [comment]
By the way, you could even have
```julia
Base.:*(variable::VariableIndex, coefficient) = LinearTerm(variable, coefficient)
Base.:*(coefficient, variable::VariableIndex) = LinearTerm(variable, coefficient)
```
as a way to construct these.

**Comment by mlubin** [comment]
`LinearTerm.(variable, coefficient)` is enough and also implicitly checks for dimension mismatches.

**Comment by blegat** [comment]
@mlubin What do you mean by "in place" ? You would do
```julia
mapvariables(varmap::Function, term::LinearTerm) = LinearTerm(varmap(term.variable), term.coefficient)
mapvariables(varmap::Function, f::MOI.ScalarAffineFunction) = MOI.ScalarAffineFunction(mapvariables(varmap, f.terms), f.coefficients, f.constant)
```

@tkoolen How would you adapt `VectorAffineFunction` ?

**Comment by mlubin** [comment]
@blegat by "in place" I mean a version that modifies the original function and doesn't allocate a new vector.

**Comment by blegat** [comment]
Why does this forces us to modify it in place ? In the example I have written above, they are not modified in place.

**Comment by tkoolen** [comment]
@blegat, that works fine, but it would allocate about twice as much as it currently does. But see the last paragraph of https://github.com/JuliaOpt/MathOptInterface.jl/issues/211#issuecomment-364487233.

**Comment by joaquimg** [comment]
I mean that it is super useful to have a single vector with variable indices and another with coefficients. With a struct its better, I think its less natural that two vectors, but it would work fine.
I do not see a lot of user protection in MOI, then I could not see why this specific case is more important.
For instance a vector function in a set with given dimension is not protected, a user could send a vector function in a set of weird dimension. I do not think that a imperfect design at one point should imply bad design somewhere else.I think if we want to protect the user we might need a few other fixes.

**Comment by mlubin** [comment]
@tkoolen, would an inner constructor on `ScalarAffineFunction` that validates ``length(variables) == length(coefficient)`` address your concerns? (And similarly for other functions.)

**Comment by mlubin** [comment]
@joaquimg, in principle, if there are easy local improvements to the API that address safety issues then we should seriously consider implementing them. We have the ability to validate properties of functions by construction. Other issues like functions and sets with mismatching dimensions are harder to address at the API level, so we probably won't.

**Comment by tkoolen** [comment]
Re: inner constructor check: https://github.com/JuliaOpt/MathOptInterface.jl/issues/211#issuecomment-364442098, so not really, but it would help a bit.

**Comment by blegat** [comment]
Modifying in place is not really an option since the function belongs to the MOIU instance. We could copy it before modifying it in place but then there is also allocation

**Comment by mlubin** [comment]
@blegat, so? We can modify it back when we're done with it. But these optimizations should wait until we have a reasonable set of benchmarks to use for comparison.

**Comment by mlubin** [comment]
I think we should go ahead with the arrays of tuples, not only because of the argument of disallowing mismatching vectors but also because of the potential substantial performance boost. Tuples of arrays are 50% slower than arrays of tuples in my benchmark at https://github.com/JuliaOpt/MathOptInterface.jl/issues/234#issuecomment-366868878. (More allocations are needed when growing them dynamically, better locality when looping through them.) This isn't a comprehensive benchmark, but these are well-known benefits of using arrays of tuples, and I think we're just using tuples of arrays currently for legacy reasons.

One more thing to consider is if we'd like to switch from arrays to `DataStructures.OrderedDict`. There's a similar usability argument here that by using an `OrderedDict` we remove the question of how to deal with duplicate indices because they cannot exist. However, I'm a bit hesitant because it's a heavy data structure that's not in base julia. It may be appropriate to use it in JuMP but not in MOI.

**Comment by mlubin** [comment]
FYI, I'd like to push this change through after the MOI 0.2 release.
