### ISSUE TITLE
Duplicate indices for coeffs

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathOptInterface.jl#234]
Gurobi, CPLEX, Xpress and GLPK do not accept duplicate indices natively when adding constraints.

I think that forcing all solvers to allow duplicate indices in constraints is an unnecessary overhead for adding constraints.

JuMP used to collect those, is it still true?

**Comment by blegat** [comment]
It does not collect it anymore, see https://github.com/JuliaOpt/JuMP.jl/blob/c58e6f08a91e1fcfbc7cb100c86284207e2c6169/src/affexpr.jl#L153-L155. You can use `MOIU.canonical` to do that in LQOI.

**Comment by joaquimg** [comment]
`MOIU.canonical` works, but for performance I would like `MOI.unsafe_addconstraint!` that assumes no duplicate indices. Or maybe some extra argument (not a keyword one though...)

**Comment by blegat** [comment]
JuMP doesn't know whether there are duplicates so how does it know if it can call `unsafe_addconstraint!`

**Comment by joaquimg** [comment]
I am not sure how or if JuMP would use it. But someone that need to add a bunch of constraints (like cuts) where no duplicates are guaranteed they could go directly through the MOI level. If that is desired in JuMP later one, it could be a keyword or a separate macro.

**Comment by blegat** [comment]
I would rather use a new boolean field to the struct or a boolean parameter to the type than add an alternative to addconstraint!

**Comment by mlubin** [comment]
This is a very sensitive issue for performance. However, I would propose to restart the discussion by considering a data structure that disallows both duplicates and mismatched input lengths (#211), i.e., `Dict{VariableIndex,T}`. We should benchmark this (comparing with the current data structure) and then decide which performance compromises we need to make, if any.

**Comment by joaquimg** [comment]
Seems fair. But do we consider it a feature to have duplicates or not?

**Comment by mlubin** [comment]
```julia
using DataStructures
using Compat # AbstactDict

struct VariableIndex
    value::Int64
end

# This is critical for dictionary performance. If it's not defined,
# then dictionaries with VariableIndex keys run 3x slower.
Base.hash(vi::VariableIndex, h::UInt) = hash(vi.value, h)

function addcoefficient!(d::AbstractDict, vi::VariableIndex, coef)
    current_coef = get!(d, vi, 0.0)
    d[vi] = current_coef + coef
    return
end

function addcoefficient!(arr::Vector{Tuple{VariableIndex,Float64}}, vi::VariableIndex, coef)
    push!(arr, (vi, coef))
end

function addcoefficient!(arr::Tuple{Vector{VariableIndex},Vector{Float64}}, vi::VariableIndex, coef)
    vars, coefs = arr
    push!(vars, vi)
    push!(coefs, coef)
end


function sum_variables_twice!(container, x)
    for vi in x
        addcoefficient!(container, vi, 1.0)
    end
    for vi in x
        addcoefficient!(container, vi, 3.0)
    end
end

removeduplicates(d::Dict) = d


# Copied from JuMP
mutable struct IndexedVector{T}
    elts::Vector{T}
    nzidx::Vector{Int}
    nnz::Int
    empty::BitArray{1}
end

IndexedVector(::Type{T},n::Integer) where {T} = IndexedVector(zeros(T
,n),zeros(Int,n),0,trues(n))

function addelt!(v::IndexedVector{T},i::Integer,val::T) where T
    if val != zero(T)
        if v.empty[i]  # new index
            v.elts[i] = val
            v.nzidx[v.nnz += 1] = i
            v.empty[i] = false
        else
            v.elts[i] += val
        end
    end
    return nothing
end

function Base.empty!(v::IndexedVector{T}) where T
    elts = v.elts
    nzidx = v.nzidx
    empty = v.empty
    for i in 1:v.nnz
        elts[nzidx[i]] = zero(T)
        empty[nzidx[i]] = true
    end
    v.nnz = 0
end

function removeduplicates(arr::Vector{Tuple{VariableIndex,Float64}}, tmprow)
    for (vi, coef) in arr
        addelt!(tmprow, vi.value, coef)
    end
    nnz = tmprow.nnz
    newarr = Vector{Tuple{VariableIndex,Float64}}()
    sizehint!(newarr, nnz)
    for i in 1:nnz
        idx = tmprow.nzidx[i]
        push!(newarr, (VariableIndex(idx),tmprow.elts[idx]))
    end
    empty!(tmprow)
    return newarr
end

function removeduplicates(arr::Tuple{Vector{VariableIndex},Vector{Float64}}, tmprow)
    vars, coefs = arr
    for i in 1:length(vars)
        addelt!(tmprow, vars[i].value, coefs[i])
    end
    nnz = tmprow.nnz
    newvars = Vector{VariableIndex}()
    newcoeffs = Vector{Float64}()
    sizehint!(newvars, nnz)
    sizehint!(newcoeffs, nnz)
    for i in 1:nnz
        idx = tmprow.nzidx[i]
        push!(newvars, VariableIndex(idx))
        push!(newcoeffs, tmprow.elts[idx])
    end
    empty!(tmprow)
    return newvars, newcoeffs
end

function test_dict(x)
    d = Dict{VariableIndex,Float64}() 
    sum_variables_twice!(d, x)
    @assert length(d) == length(x)
end

function test_ordered_dict(x)
    d = OrderedDict{VariableIndex,Float64}() 
    sum_variables_twice!(d, x)
    @assert length(d) == length(x)
end

function test_array_of_tuples(x, tmprow)
    arr = Vector{Tuple{VariableIndex,Float64}}() 
    sum_variables_twice!(arr, x)
    newarr = removeduplicates(arr, tmprow)
    @assert length(newarr) == length(x)
end

function test_tuple_of_arrays(x, tmprow)
    arr = (Vector{VariableIndex}(),Vector{Float64}())
    sum_variables_twice!(arr, x)
    newarr = removeduplicates(arr, tmprow)
    @assert length(newarr[1]) == length(x)
    @assert length(newarr[2]) == length(x)
end

nonzeros_in_expression = 5
N = 1000

tmprow = IndexedVector(Float64, N)


using BenchmarkTools

x = [VariableIndex(mod(345*i,N)) for i in 1:nonzeros_in_expression]
@assert allunique(x)

@btime test_dict($x)
@btime test_ordered_dict($x)
@btime test_array_of_tuples($x, $tmprow)
@btime test_tuple_of_arrays($x, $tmprow)
```

Some food for thought. I threw together the above benchmark that compares:
- `Dict`
- `OrderedDict`
- Arrays of index/value tuples (proposed in #211)
- Separate index/value arrays (current implementation)

The test is to add a few nonzero coefficients to a linear expression and then remove duplicates. For the array implementations, duplicates are removed using IndexedVector which has been used for a long time in JuMP. I'm ignoring an additional complication here that MOI indices don't necessarily fall in a small range, so IndexedVector will require an extra map to use (not implemented). For the dictionary implementations, duplicates are never created, and the implementation is arguably simpler. It turns out that **separate index/value arrays are the slowest!**

On 0.7 (in same order as listed above):
```
  404.885 ns (4 allocations: 608 bytes)
  601.898 ns (11 allocations: 1.02 KiB)
  463.680 ns (7 allocations: 1.41 KiB)
  726.427 ns (15 allocations: 1.72 KiB)
```

On 0.6
```
  719.578 ns (4 allocations: 608 bytes)
  862.066 ns (11 allocations: 1.02 KiB)
  462.355 ns (7 allocations: 1.41 KiB)
  802.367 ns (16 allocations: 1.75 KiB)
```

The `Dict` implementation works great, but I'm bothered by not having a guarantee on iteration order. I think this will come back to get us later on if solvers behave slightly differently depending on the order in which coefficients are specified. Based on these results, we could consider replacing the storage in the basic `AffExpr` type in JuMP with an `OrderedDict` and the storage in `ScalarAffineExpression` with either 1) an `OrderedDict` also, or 2) an array of tuples with no duplicates allowed. We'd need to make similar changes to the rest of the functions as well.

**Comment by andyferris** [comment]
I wonder if this makes any performance impact (I didn't test it at all but it's a nice trick to not perform the hashing and internal index lookup twice):
```julia
function addcoefficient!(d::Dict, vi::VariableIndex, coef)
    index = Base.ht_keyindex2!(d, vi)
    if index > 0
        @inbounds d.keys[index] = vi
        @inbounds d.values[index] += coef
    else
        @inbounds Base._setindex!(d, coef, vi, -index)
    end
end
```
(adapted from `setindex!` for `Dict` [here](https://github.com/JuliaLang/julia/blob/master/base/dict.jl#L400-L413))

**Comment by blegat** [comment]
I tried @andyferris 's suggestion, it indeed improve the performance of Dict. Note that `Base.setindex!(::Dict, ...)` has been updated recently so we now need
```julia
function addcoefficient!(d::Dict, vi::VariableIndex, coef)
    index = Base.ht_keyindex2!(d, vi)
    if index > 0
        d.age += 1
        @inbounds d.keys[index] = vi
        @inbounds d.vals[index] += coef
    else
        @inbounds Base._setindex!(d, coef, vi, -index)
    end
end
```
Without this change, we have:
With 5 nonzero elements (equivalent to @mlubin 's benchmark)
```
  195.359 ns (4 allocations: 608 bytes)
  342.691 ns (9 allocations: 752 bytes)
  121.711 ns (4 allocations: 640 bytes)
  222.865 ns (9 allocations: 736 bytes)
```
With 100 nonzero elements:
```
  3.629 μs (10 allocations: 6.61 KiB)
  4.672 μs (19 allocations: 6.39 KiB)
  1.502 μs (8 allocations: 8.34 KiB)
  2.626 μs (17 allocations: 8.69 KiB)
```
Now with @andyferris 's suggestion (only the Dict's timing should change)
With 5 nonzero elements (equivalent to @mlubin 's benchmark)
```
  159.936 ns (4 allocations: 608 bytes)
  333.932 ns (9 allocations: 752 bytes)
  120.934 ns (4 allocations: 640 bytes)
  221.039 ns (9 allocations: 736 bytes)
```
With 100 nonzero elements:
```
  2.875 μs (10 allocations: 6.61 KiB)
  4.638 μs (19 allocations: 6.39 KiB)
  1.543 μs (8 allocations: 8.34 KiB)
  2.618 μs (17 allocations: 8.69 KiB)
```

I would be in favor of
```julia
struct ScalarAffineFunction{T}
    terms::Vector{Tuple{VariableIndex, T}}
    constant::T
    noduplicate::Bool # true means that we know there is no duplicate, false means there might be
end
ScalarAffineFunction(terms, constant) = ScalarAffineFunction(terms, constant, false)
function mergeduplicates(f::ScalarAffineFunction)
    if f.noduplicate
        f
    else
        terms = # merge duplicates in f.terms
        ScalarAffineFunction(terms, f.constant, true)
    end
```
If a solver does not care about duplicates, it just takes `f.terms` and `f.constant` as it is given.
If a solver wants no duplicate it calls `mergeduplicates`. If the user (e.g. JuMP or something else) has already removed duplicates, it will be a no-op, otherwise it removes the duplicates.

**Comment by mlubin** [comment]
I don't like having an extra flag in the struct. Either:

- Use a `Vector{Tuple{VariableIndex, T}}` and allow duplicates in the format. Solvers are responsible for clearing them later or throwing an error (like they would for any invalid data) if they want to be grumpy about it. Or,
- Use an `OrderedDict{VariableIndex, T}` so that duplicates cannot possibly exist.

That said, when we switch JuMP's `AffExpr` to use `OrderedDict` it won't be generating expressions with duplicates, so the grumpy option might work reasonably well for solvers after that happens.

**Comment by blegat** [comment]
Related: on https://github.com/rdeits/ConditionalJuMP.jl/pull/42, @vtjeng suggests that for up to 100 variables, the simple inplace O(N^2) approach is faster as it does not allocate anything.

**Comment by rdeits** [comment]
I'm really excited to see this happening! Avoiding duplicates entirely would make ConditionalJuMP's work much easier. 

As for the benchmarks in https://github.com/rdeits/ConditionalJuMP.jl/pull/42 I think the big difference is that the inplace O(N^2) approach avoided allocating a *new* dict to do the de-duplication, but if we change AffExpr to use a Dict internally then we only need to worry about the *difference* between an OrderedDict and the pair of Vectors that AffExpr currently uses. So I'd be generally in favor of the change to OrderedDict. 

@tkoolen also has some fancy custom Associative types in RigidBodyDynamics.jl like https://github.com/JuliaRobotics/RigidBodyDynamics.jl/blob/c498998b7020af5fea89fed9e12c6c0ca0ac3593/src/custom_collections.jl#L133 although I'm not sure if they'd be useful here.

**Comment by vtjeng** [comment]
@blegat just as a point of clarification - 100 variables is just an approximate threshold, and for proper attribution, it was @rdeits that observed this (I merely wrote a wrapper that selected the appropriate approach).

**Comment by mlubin** [comment]
We should update MOI documentation to mention that JuMP will not generate duplicates.
