### ISSUE TITLE
supports vs canset

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#295]
Why do we have both
```julia
MOI.canset(model, MOI.NLPBlock())
```
and
```julia
MOI.supports(model, MOI.NLPBlock())
```
?

@blegat

**Comment by mlubin** [comment]
This is potentially more confusing than helpful for users and implementers of solver interfaces. If the optimizer `supports` an attribute but `canset` would be false, why not just throw an error explaining why the attribute is not settable right now?

**Comment by blegat** [comment]
`supports` is the replacement of `cancopy`. It is useful for `copy`-only solvers as we can check programatically if a `copy` might fail. For solvers that support `addconstraint!` and `set!`, it might seem cumbersome to also implement `supports` and `supportsconstraint`. We might change the fallback to
```julia
supports(m::ModelLike, attr...) = canset(m, attr)
```
so that solvers for which canset is equivalent to supports only need to implement `canset`.

**Comment by mlubin** [comment]
Could you provide an example where we need to distinguish between `supports` and `canset` programmatically? Default fallbacks help but don't really remove the additional complexity of having these two concepts.

**Comment by blegat** [comment]
If a user adds a rotated second order cone constraints, we need to know whether the optimizer supports it to know whether we need to transform it into a second order cone constraint (e.g. using a bridge) or to leave the constraint as it is.

**Comment by mlubin** [comment]
Why not use `supportsconstraint` instead of `canaddconstraint` in that context?

**Comment by blegat** [comment]
That's exactly my point, we need `supportsconstraint` in this situation

**Comment by blegat** [comment]
We need `canaddconstraint` for the CachingOptimizer to see whether the optimizer supports adding a constraint or it needs to go in `EmptyOptimizer` state
https://github.com/JuliaOpt/MathOptInterface.jl/blob/7164fdc573f3f92acb93de1bf18a3d3bd5e315c7/src/Utilities/cachingoptimizer.jl#L213-L215

**Comment by mlubin** [comment]
I'm also proposing to replace that usage of `canaddconstraint` with `supportsconstraint`.

**Comment by blegat** [comment]
But `supportsconstraint` does not help distinguishing whether the solver supports adding constraints or needs to be emptied and needs to be passed the whole problem using `copy!`.

**Comment by mlubin** [comment]
What about `MOI.canaddconstraint(m.optimizer) && MOI.supportsconstraint(m.optimizer, typeof(func), typeof(set))` in this case?

Why does "whether the solver supports adding constraints" need to depend on the type of constraint, beyond what's already encoded in `MOI.supportsconstraint`?

**Comment by blegat** [comment]
Some solvers might, after `optimize!` is called, support adding some kind of constraints but not other kind of constraints, even if they support these constraints.

**Comment by mlubin** [comment]
Ok, good point. I would question if the extra complexity in MOI is worth it to handle that case. Users will be able to work around an error message by manually detaching the optimizer.

**Comment by blegat** [comment]
We could define `supports` and `supportsconstraint` on the type of the model instead of on the model itself.
That would clarify the distinction between `canset` and `supports` (and `canaddconstraint` and `supportsconstraint`) and make it clearer that the `supports` version is not about the current state of the model (an prevent model implementation to make it depend on it).
This is also in accordance to [this tip](https://docs.julialang.org/en/stable/manual/style-guide/#Avoid-confusion-about-whether-something-is-an-instance-or-a-type-1) of the Julia style guide.
What do you think ?

**Comment by mlubin** [comment]
@blegat that makes sense. Back in MPB time when the parameters were attached to the solver object, it made sense that you might have the set of problem supported depend on the solver parameters that are set. Given that we don't have this anymore, let's try having `supports` and `supportsconstraint` be defined for the type.

I'm still questioning the value of `canget` where the value can change at runtime. Are there meaningful cases where we need this for dispatch? Why not just call `get` and throw an error?

**Comment by ccoffrin** [comment]
BTW, I got confused about the difference between `canget` and `supports`, at the least a more specific name might be warranted.
