### ISSUE TITLE
UniversalFallback should throw key error rather than return canget == false if attribute partially set

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterface.jl#302]
https://github.com/JuliaOpt/MathOptInterface.jl/blob/7164fdc573f3f92acb93de1bf18a3d3bd5e315c7/src/Utilities/universalfallback.jl#L54-L57

The check on the length of the dictionary means that:
```julia
m = Model()
@variable(m, x, start = 1)
@variable(m, y)
JuMP.startvalue(x)
```
gives
```
 Attribute MathOptInterface.VariablePrimalStart() not accessible
  Stacktrace:
   [1] get(::MathOptInterface.Utilities.CachingOptimizer, ::MathOptInterface.VariablePrimalStart, ::MathOptInterface.VariableIndex) at /home/mlubin/.julia/v0.6/MathOptInterface/src/Utilities/cachingoptimizer.jl:380
   [2] get(::JuMP.Model, ::MathOptInterface.VariablePrimalStart, ::JuMP.Variable) at /home/mlubin/.julia/v0.6/JuMP/src/JuMP.jl:379
   [3] startvalue(::JuMP.Variable) at /home/mlubin/.julia/v0.6/JuMP/src/variables.jl:379
```
The attribute values should be available immediately after you set them, and there should be a key error in the case that you ask for a value that's not defined.

**Comment by blegat** [comment]
In the doc, we have say that `canget` returns `true` if it is

> applied to *every* variable

https://github.com/JuliaOpt/MathOptInterface.jl/blob/9f75cea0bc305d0628827b29427a329809b0f33d/src/attributes.jl#L141-L143

**Comment by mlubin** [comment]
It's evident to me that this is a bad design. `Attribute MathOptInterface.VariablePrimalStart() not accessible` is an incorrect and misleading error message in this situation. If an attribute is partially set, the model is still responsible for that attribute, and `get` should be called. The model may choose to return an error if it can't access the attribute, and that's ok. We might need to brainstorm a bit on how to resolve this situation and #295 now that we have a bit more experience working with MOI.

**Comment by blegat** [comment]
When `MOI.get` is called on CachingOptimizer, and `canget` is false for both the model and the optimizer, it could try to still call `get` on one of them as you suggest. It should try `get` on the one that supports this even it is not set for all variables. `supports` is probably the solution then.

If both `canget` return false, CachingOptimizer calls `support` on the optimizer, if it returns `true` it calls get on it. Otherwise it calls `get` on the `model` (the model supports everything because of the UniversalFallback).
