### ISSUE TITLE
Move MOIBridges.jl to this package

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterface.jl#313]
The vote of https://github.com/JuliaOpt/MathOptInterface.jl/issues/173 was against moving MOIBridges to MOI but things have changed now as MOITest and MOIUtilities have been moved to MOI.
What do you prefer ?
* Move it to MOI under a Bridges submodule :+1: 
* Move it to MOI under a Utilities.Bridges submodule :tada: 
* Leave it separate (and maybe rename it to MathOptBridges) :-1: 

It opens the question on what we should include in this package as submodule instead of separate packages
1) Modules needed to test MOI (Test, Utilities)
2) Modules defining new MOI layers needed by JuMP (Bridges)
3) Modules defining new MOI layers (...)

For now we only include the first category and Bridges has been kept in separate packages. Including Bridges in this package means we also want to include the second category. I think it is important to maintain the third category out of MOI to promote a decentralized ecosystem. We don't want to send the message that MOI layers defined as MOI submodules are "better" that MOI layers defined outside.

**Comment by mlubin** [comment]
My main concern is that if core solvers like [Ipopt](https://github.com/JuliaOpt/Ipopt.jl/pull/108) need to use the bridges to pass MOI tests, then bridges should be in this package, because it will just be painful to depend on linked versions of MOI and MOIBridges. If solvers shouldn't be using bridges in tests, then we need to add clear guidance on this in the documentation.

**Comment by odow** [comment]
I am more and more in favour of bigger repositories.

**Comment by blegat** [comment]
> it will just be painful to depend on linked versions of MOI and MOIBridges

The solver just have to do in `REQUIRE`
```
MathOptInterface 0.n 0.n+1
```
and in `test/REQUIRE`
```
MathOptBridges 0.x.y
```
if the bridges used by the tests were added in 0.x.y.
When a new version of MOI is released, it needs to update
```
MathOptInterface 0.n+1 0.n+2
```
but it does not need to change the `test/REQUIRE` file.

> I am more and more in favour of bigger repositories.

Do you mean big repo containing several packages (I have heard it will be supported by Pkg3) or big package ?
As I said in my earlier comment, we need to be careful of the message we send.
The thing I like with MOIBridges being in a separate package is that it shows how deeply integrated, an MOI extension can be even if it is not inside the JuMP package or the MOI package. It sends the message that extensions to JuMP and/or MOI can really feel like first class to the user and not some weird shaky patchy addition. As MOIBridges is part of the second category of my earlier post, we could argue that this is the reason it is included in MOI but the fact that MOIBridges part of MOI may feel like the consequence of a bad design of MOI that doesn't allow bridges to be decoupled from the MOI package while it's not.

Note that two examples of the 3rd category are LQOI and SDOI which are not part of MOI and they are also required by some solvers. Would you think that they should also be part of MOI ?

**Comment by mlubin** [comment]
Whenever a new v0.x MOI release is tagged, we'll need to tag or update requirements for MOIBridges before there's a satisfiable combination of the two packages (assuming MOIBridges has a tight dependency on MOI).

> As I said in my earlier comment, we need to be careful of the message we send.

I disagree that sending a message about extensibility should be a major factor in the decision. Software engineering and maintainability concerns are more important. If we want to have people feel comfortable writing extensions, I would argue that a clean API with good documentation and examples is far more important than the structure of the packages. Having code for essential functionality (e.g., what we need to match the current JuMP 0.18 functionality) spread across multiple repositories is the shaky/patchy practice, IMO. Let's build a strong house as an example so that others can follow it and build their own.

This does leave the option open to move some "essential" bridges into MOI and keep more experimental or new bridges in a separate package (i.e., as an example of an extension).

> Note that two examples of the 3rd category are LQOI and SDOI which are not part of MOI and they are also required by some solvers. Would you think that they should also be part of MOI ?

Actually yes. LQOI and SDOI are sore points in the current setup. They're not well documented and I've seen multiple people confused about what they do and how they should be used. We would be in a better position if they came into MOI through our rigorous code review :). I wouldn't argue that this is a top priority at the moment, however.

**Comment by blegat** [comment]
> Whenever a new v0.x MOI release is tagged, we'll need to tag or update requirements for MOIBridges before there's a satisfiable combination of the two packages (assuming MOIBridges has a tight dependency on MOI).

Yes, that adds the time of the METADATA PR getting merged.

> I disagree that sending a message about extensibility should be a major factor in the decision.

I understand this opposite concern, I suppose there is an optimal trade-off. I wouldn't be surprised if including Bridges in MOI is part of this optimal trade-off but I want to make sure that we keep in mind the concern I raised in the earlier comment and that if we starting including everything inside MOI we might cross the optimal trade-off :-P

> it would be reasonable to wait and see how that functionality works in Pkg3.

I agree

**Comment by mlubin** [comment]
What about just moving `SplitIntervalBridge`? That's the one that Ipopt uses.

**Comment by mlubin** [comment]
Which bridges are needed by convex solvers to pass contconic tests?

**Comment by blegat** [comment]
`geomean` and `det` bridges are needed by all SDP solvers and `soctopsd` is needed by CSDP, SDPA, DSDP, SDPLR. The other bridges that will be added are also needed by a non-empty set of solvers.
Bridges like sum of squares bridges though will probably be defined by SumOfSquares.jl outside of MOI, and the tests will also be in SumOfSquares.jl
