### ISSUE TITLE
size/dimension ambiguity

### ISSUE THREAD

**Issue by mohamed82008** [JuliaOpt/MathOptInterface.jl#412]
MOI is inconsistent in its use of the word `dimension`, e.g. https://github.com/JuliaOpt/MathOptInterface.jl/blob/585a9593d9d093d60397de22295899b4d2aef6e1/src/sets.jl#L275 and a few other places in this file.

**Comment by blegat** [comment]
What is inconsistent ?

**Comment by odow** [comment]
The function `dimension` is a well-defined concept. It is the output dimension of the set. 

The interpretation of the field `dimension` in the set you linked to is also well-defined. It is the dimension of the matrix.

The dimension of the set is not the same as the dimension of the matrix so `a.dimension != dimension(a)`.

I'm not sure it is correct to use `size` because then the struct should store a tuple, rather than just the side length.

**Comment by mohamed82008** [comment]
Nothing says `size` should be a tuple, for square matrices it makes perfect sense if `size` is an integer. While the word `dimension` is correctly used with 2 different meanings, this is really the problem, I think it is less ambiguous to use different words for different concepts. Something like `matrix_dimension` would be better than simply `dimension`, but then `size` is shorter and reminds us of `Base.size`. `matrix_size` is another option.

**Comment by mlubin** [comment]
I agree that there's a clarity issue if you read:
```julia
struct PositiveSemidefiniteConeTriangle <: AbstractVectorSet
    dimension::Int
end
```
and have to ask which dimension the field is referring to. What about renaming this field to `side_dimension`?

**Comment by mohamed82008** [comment]
Coming up in a PR.
