### ISSUE TITLE
nonpositives to nonnegatives bridge

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathOptInterface.jl#516]
would be convenient for conic solvers that understand the nonnegative orthant cone but not the nonpositive orthant cone

**Comment by blegat** [comment]
I agree, this could be a `FlipSideBridge` that also do the transformation between GreaterThan and LessThan

**Comment by blegat** [comment]
It might need to be 4 different bridges instead of one supporting the 4 transformation to be usable with the SingleBridgeOptimizer. Since the SingleBridgeOptimizer applies anything transformation it supports without checking whether the optimizer supports anything, it will probably do an infinite loop by transforming back and forth
