### ISSUE TITLE
Questions implementing a wrapper

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#71]
I'm going to use this issue as a collection place for a range of questions I have implementing the CPLEX solver wrapper:

**On the purpose of low-level interface**
- [x] should we expose the full (potentially ad-hoc, complicated) API, or a simplified one to satisfy MOI requirements. **Don't remove existing functionality**

**On variable bounds**
- [x] is `addconstraint!(m, v::VectorOfVariables, set::LessThan{Float64})` a valid constraint? **oO**
- [x] should `addconstraint!(m, v::VectorOfVariables, set::Vector{Union{LessThan{Float64}, GreaterThan{Float64}, EqualsTo{Float64}, Interval{Float64}}})` be a valid constraint so users can set bounds all at once? **No. <s>Overload the broadcast operator https://github.com/JuliaOpt/MathOptInterface.jl/issues/63#issuecomment-317545139</s> https://github.com/JuliaOpt/MathOptInterface.jl/issues/63#issuecomment-317526848**

**Comment by joaquimg** [comment]
Maybe with plural: `addconstraints!(m, v::VectorOfVariables, set::Vector{Union{LessThan{Float64}, GreaterThan{Float64}, EqualsTo{Float64}, Interval{Float64}}})` this could return vector of references...

**Comment by mlubin** [comment]
>  is ``addconstraint!(m, v::VectorOfVariables, set::LessThan{Float64})`` a valid constraint?

We can't prevent a solver from recognizing the constraint, but no (https://github.com/JuliaOpt/MathOptInterface.jl/pull/64). `VectorOfVariables` is a vector-valued function and `LessThan` is a scalar-input set.

> should ``addconstraint!(m, v::VectorOfVariables, set::Vector{Union{LessThan{Float64}, GreaterThan{Float64}, EqualsTo{Float64}, Interval{Float64}}})`` be a valid constraint so users can set bounds all at once?

It's one function per set in MOI. `VectorOfVariables` is one function, so it doesn't make sense to provide multiple sets there. We could define ``addconstraints!(m, ::Vector{F}, ::Vector{S})`` to return a vector of `ConstraintReference{F,S}` for concrete `F` and `S`. I don't see a reasonable (type-stable) way to do that when `S` is a union type .

> should we expose the full (potentially ad-hoc, complicated) API, or a simplified one to satisfy MOI requirements.

Up to the discretion of whoever is writing the MOI wrapper. Keep in mind that eventually there will be a desire for a standalone and feature complete CPLEX wrapper (https://github.com/JuliaOpt/MathOptInterface.jl/issues/22). It's not our job to do that, but removing existing wrappers for C functions that aren't used in MOI seems unnecessary. It's fine with me to remove higher-level helper functions that aren't needed for MOI.

**Comment by IssamT** [comment]
`SolverInstance(solver::AbstractSolver)` is supposed to create the new model to be solved. Is there a way to tell a solver who is able to solve different types of models , requiring different setups, which type of model you want to solve? (for example what type of constraints will be added in this model)

**Comment by IssamT** [comment]
To keep MOI generic the type of the model, in my opinion, should be just an optional argument. For some model types like LPs where there is no variable type and only linear constraints, it could be nice for the solver to know it.

CLP for example has:
```julia
LinearQuadraticModel(s::ClpSolver) = ClpMathProgModel(;s.options...)
ConicModel(s::ClpSolver) = LPQPtoConicBridge(LinearQuadraticModel(s))
```

For Cplex I think that if you declare the problem as LP you can't add integer variables afterwards. 

MOIU despite adding an intermediary layer doesn't solve the issue because it doesn't tell you anything about what the user is planning to add after the `optimize!`

**Comment by IssamT** [comment]
```julia
macro instance(instancename, scalarsets, typedscalarsets, vectorsets, typedvectorsets, scalarfunctions, vectorfunctions)
```

This may be a partial answer to my question, for solvers which rely on MOIU

**Comment by joaquimg** [comment]
> MOIU despite adding an intermediary layer doesn't solve the issue because it doesn't tell you anything about what the user is planning to add after the optimize!

For stuff being added after `optimize!` we should have other methods like: `SupportsAddVariableAfterSolve`.

**Comment by joaquimg** [comment]
CLP has multiple solvers?

**Comment by IssamT** [comment]
One solver but two possible models (solver instances)

**Comment by IssamT** [comment]
We can maybe use a `SolverInstanceAttribute` for this.

cplex example of the function to be called by the attribute setter: 
https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.7.1/ilog.odms.cplex.help/refcallablelibrary/cpxapi/chgprobtype.html

And if a solver needs the problem type before creating the instance we can create the instance only on julia side and delay calling the true constructor until the attribute has been set.

**Comment by mlubin** [comment]
> We can maybe use a `SolverInstanceAttribute` for this.

I don't have a good understanding of what CPLEX's problem type actually means. Using a `SolverInstanceAttribute` is possible but on a first glance it seems like it would have to be something solver specific because other solvers have either different concepts or no concepts at all of a problem type.

**Comment by odow** [comment]
CPLEX's problem type is used to dispatch on different [optimize calls](https://github.com/JuliaOpt/CPLEX.jl/blob/master/src/cpx_solve.jl#L1-L13). For instance, if the problem type is MILP, a call to `CPXlpopt` will error. It's pretty annoying as you have to keep track of what type of problem you're solving, rather than letting CPLEX figure it out.

**Comment by joaquimg** [comment]
@odow I was looking at the latest CPLEX MOI. 

It seems that there is a lot of work around exposing all the MOI flexibility which differs from MPB that was much simpler.

You have written the code so that it is explicit when you use a cplex function. I listed most of them here https://gist.github.com/joaquimg/e793e5a0677d77b0e190df556f58e178

Many of them map DIRECTLY into some functions of Xpress and Gurobi. And some other need simple adaptations.

What do you think about having a intermediate package (SomeCleverNameOptInterface) to make it easier to wrap the 3 of them in MOI? just like SOI does for its solvers... Specific corner cases could be held by the wrappers (CPLEXMathOptInterface...)

**Comment by joaquimg** [comment]
If I copy what you have done and change a few function I get 90% of the functionality...

**Comment by odow** [comment]
I'm a bit busy writing up bits of my thesis for a few weeks., but this seems sensible.

**Comment by joaquimg** [comment]
I started the experiment: https://github.com/joaquimg/LinQuadOptInterface.jl
I am terrible at naming things, so please give me better ideas.
The Xpress version is in LQOI branch in Xpress.jl and the CPLEX version consists of simply replacing "lqs" by "cpx"
It looks good, Xpress is passing almost everything it was passing before in less than 400 lines. This way gurobi might be very easy. Plus performance optimization would go for the 3 of them at the same time.

**Comment by blegat** [comment]
I am glad to see that much of the code can be shared between the LQ solvers ! The name LinQuadOptInterface seems fine to me, it is consistent with SOI. I wonder if GLPK and Clp can use LQOI.

**Comment by odow** [comment]
This discussion seems mostly resolved.
