### ISSUE TITLE
Interval sets

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterface.jl#88]
Why do we need `Reals`, `Zeros`, `Nonnegatives`, `Nonpositives`, `GreaterThan`, `LessThan`, `EqualTo`, and `Interval`?

```julia
struct Interval{T}
    lower::T
    upper::T
end
struct Intervals{T}
    lower::Vector{T}
    upper:Vector{T}
end
# or just riffing here...
struct VectorOfIntervals{T}
    intervals::Vector{Interval{T}}
end

# variable bounds
addconstraint!(m, ::SingleVariable, ::Interval)
addconstraint!(m, ::SingleVariable, ::Intervals) # error. Not valid

addconstraints!(m, ::VectorOfVariables, ::Interval) # every variable has the same bound
addconstraints!(m, ::VectorOfVariables, ::Intervals) # every variable has different bound

# constraints
addconstraints!(m, ::ScalarAffineFunction, ::Interval) 
addconstraints!(m, ::ScalarAffineFunction, ::Intervals) # error not valid

addconstraints!(m, ::VectorAffineFunction, ::Interval) # every constraint has same set
addconstraints!(m, ::VectorAffineFunction, ::Intervals) # every constraint has different set 

addconstraints!(m, ::ScalarQuadraticFunction, ::Interval) 
addconstraints!(m, ::ScalarQuadraticFunction, ::Intervals) # error not valid

addconstraints!(m, ::VectorQuadraticFunction, ::Interval) # every constraint has same set
addconstraints!(m, ::VectorQuadraticFunction, ::Intervals) # every constraint has different set 
```

You can have `Nonpositives(dim) = Intervals(fill(-Inf, dim), fill(0.0, dim))` if you really want.

**Comment by mlubin** [comment]
`Zeros`, `Nonnegatives`, and `Nonpositives` are natural sets for conic modeling. I wouldn't want to remove them just because there's a way they can be transformed to interval constraints. People may think in terms of modifying the constant in a `Nonnegatives` constraint rather than modifying an open interval.

There was also an effort to avoid sets which require GC-tracked parameters parameters like Vectors but not sure if that matters so much because the functions definitely have them.

**Comment by blegat** [comment]
Do we have duals for intervals ? Another issue with Intervals is that if you want to do one-sided inequality you need to use floating point arithmetic.

**Comment by mlubin** [comment]
Is there a discussion to continue here?

**Comment by odow** [comment]
Nope. I'm happy with that answer
